<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[This is failed log from reporter.log]]>
    </line>
    <line>
      <![CDATA[This is failed log from reporter.log]]>
    </line>
  </reporter-output>
  <suite started-at="2023-02-23T07:10:26Z" name="Default Suite" finished-at="2023-02-23T07:10:32Z" duration-ms="6659">
    <groups>
    </groups>
    <test started-at="2023-02-23T07:10:26Z" name="UTH_UK_AssesmentPortal" finished-at="2023-02-23T07:10:32Z" duration-ms="6659">
      <class name="Main.testcase.demo">
        <test-method is-config="true" signature="LunchBrowserAndNavigateToUrlSetup()[pri:0, instance:Main.testcase.demo@1dd92fe2]" started-at="2023-02-23T12:40:26Z" name="LunchBrowserAndNavigateToUrlSetup" finished-at="2023-02-23T12:40:31Z" duration-ms="5572" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LunchBrowserAndNavigateToUrlSetup -->
        <test-method signature="test(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Main.testcase.demo@1dd92fe2]" started-at="2023-02-23T12:40:32Z" name="test" data-provider="TestScript_1" finished-at="2023-02-23T12:40:32Z" duration-ms="12" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[John Doe]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ThisIsNotAPassword]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Medicaid]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Yes]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.util.Properties.getProperty(String)" because "this.property" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "this.property" is null
	at Com.Base.resources.base.openurlandverifyPage(base.java:52)
	at Reuseable.testcase.Uth_uk_assesment.uthuk_Assesment_Register(Uth_uk_assesment.java:18)
	at Main.testcase.demo.test(demo.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[This is failed log from reporter.log]]>
            </line>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method is-config="true" signature="FailureSetup(org.testng.ITestResult)[pri:0, instance:Main.testcase.demo@1dd92fe2]" started-at="2023-02-23T12:40:32Z" name="FailureSetup" finished-at="2023-02-23T12:40:32Z" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test status=FAILURE method=demo.test(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Main.testcase.demo@1dd92fe2] output=This is failed log from reporter.log]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FailureSetup -->
        <test-method signature="test(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Main.testcase.demo@1dd92fe2]" started-at="2023-02-23T12:40:32Z" name="test" data-provider="TestScript_1" finished-at="2023-02-23T12:40:32Z" duration-ms="1" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[John Doe]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ThisIsNotAPassword]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[None]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Yes]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.util.Properties.getProperty(String)" because "this.property" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.Properties.getProperty(String)" because "this.property" is null
	at Com.Base.resources.base.openurlandverifyPage(base.java:52)
	at Reuseable.testcase.Uth_uk_assesment.uthuk_Assesment_Register(Uth_uk_assesment.java:18)
	at Main.testcase.demo.test(demo.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[This is failed log from reporter.log]]>
            </line>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method is-config="true" signature="FailureSetup(org.testng.ITestResult)[pri:0, instance:Main.testcase.demo@1dd92fe2]" started-at="2023-02-23T12:40:32Z" name="FailureSetup" finished-at="2023-02-23T12:40:32Z" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test status=FAILURE method=demo.test(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Main.testcase.demo@1dd92fe2] output=This is failed log from reporter.log]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FailureSetup -->
      </class> <!-- Main.testcase.demo -->
    </test> <!-- UTH_UK_AssesmentPortal -->
  </suite> <!-- Default Suite -->
</testng-results>
